# create version/tag information for pihole recipe to build versions file
# matches pihole 6.1.2 build

BB_FTL_VERSION = "v6.2.3"
BB_FTL_BRANCH = "master"
FTL_SRCREV = "88737f6248cd3df3202eed72aeec89b9fb572631"
# this is first 8 chars of SRCREV
BB_FTL_HASH = "88737f62" 

BB_WEB_VERSION = "v6.2.1"
BB_WEB_BRANCH = "master"
WEB_SRCREV = "cc1cc2859ecb543e3cf7f1874e8a74ef0bd49b8a"
BB_WEB_HASH = "cc1cc285"

BB_CORE_VERSION = "v6.1.2"
BB_CORE_BRANCH = "master"
CORE_SRCREV = "ec892ec096cd1adb90b0209d4c0a155953faf813"
BB_CORE_HASH = "ec892ec0"