# create version/tag information for pihole recipe to build versions file

BB_FTL_VERSION = "v6.1"
BB_FTL_BRANCH = "master"
FTL_SRCREV = "a3313229c21eefcb608e5d30b7255723d9efa3a9"
# this is first 8 chars of SRCREV
BB_FTL_HASH = "a3313229" 

BB_WEB_VERSION = "v6.1"
BB_WEB_BRANCH = "master"
WEB_SRCREV = "1eaddca8db2e54a57e682633ea31096a3166b082"
BB_WEB_HASH = "1eaddca8"

BB_CORE_VERSION = "v6.0.6"
BB_CORE_BRANCH = "master"
CORE_SRCREV = "0f7803b7753b581ed747eb6398be0c78dbfdc845"
BB_CORE_HASH = "0f7803b7"