# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += " \
	${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend \
	"

BBFILE_COLLECTIONS += "meta-hunter-embedded"
BBFILE_PATTERN_meta-hunter-embedded = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-hunter-embedded = "20"

LAYERSERIES_COMPAT_meta-hunter-embedded = "scarthgap"

LAYERDEPENDS_meta-hunter-embedded = "core"
LAYERDEPENDS_meta-hunter-embedded += "openembedded-layer"
LAYERDEPENDS_meta-hunter-embedded += "meta-python"
LAYERDEPENDS_meta-hunter-embedded += "networking-layer"

