require conf/distro/poky.conf

DISTRO="pihole"


# specify per machine which device tree files to load
RPI_KERNEL_DEVICETREE_OVERLAYS:raspberrypi4 = " overlays/uart1.dtbo"
RPI_KERNEL_DEVICETREE:raspberrypi4 = " broadcom/bcm2711-rpi-4-b.dtb"


MACHINE_FEATURES:raspberrypi4=" sdio"

# force use of u-boot, put in distro at this point as we only support rpis
RPI_USE_U_BOOT = "1"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
KERNEL_IMAGETYPE = "zImage"
KERNEL_BOOTCMD = "bootz"

# enable RAUC
DISTRO_FEATURES:append = " rauc"

# Settings for meta-rauc-raspberry-pi
IMAGE_INSTALL:append = " rauc"
IMAGE_FSTYPES:append = " ext4"
WKS_FILE = "sdimage-dual-raspberrypi.wks.in"
